/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Contador contador = new Contador();
        System.out.println("Valor inicial: " + contador.GetContador());
        contador.Incrementador();
        System.out.println("Valor valor atual: " + contador.GetContador());
    }
}